# Generated by Django 5.2.11 on 2026-02-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_rollno_student_roll_no_remove_student_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
