# Generated by Django 5.2.11 on 2026-02-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fee_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='semester',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
