# Generated by Django 5.2.11 on 2026-02-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
